s11-selfstudy/Models/Course.cs
using System.Collections;
using System.ComponentModel.DataAnnotations;

namespace s11_selfstudy.Models
{
    public class Course
    {
        [Key]
        public int Id { get; set; }

       
        [Required]
       
        [StringLength(50, MinimumLength = 10)]
        public string Title { get; set; } = null!;

        [Required]
        public Stack Stack { get; set; }

        [Required]
        public string Description { get; set; } = null!;

        [Required]
        
        [DataType(DataType.Currency)]
        public double Price { get; set; }

        [Required]
       
        [DataType(DataType.Url)]
        public string StackUrl { get; set; } = null!;

        [Required]
        
        [DataType(DataType.ImageUrl)]
        [Display(Name = "Logo")]
        public string Logo { get; set; } = null!;

    }
}

s11-selfstudy/Models/ErrorViewModel.cs
namespace s11_selfstudy.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

s11-selfstudy/Models/Stack.cs
using System.ComponentModel.DataAnnotations;

namespace s11_selfstudy.Models
{
    public enum Stack
    {
        MEAN,
        MERN,
        Django,
        [Display(Name = "Ruby on Rails")] Rails,
        LAMPP
    }
}

s11-selfstudy/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace s11_selfstudy.Models
{
    public class User
    {
        [Key] // Denotes Primary Key
        public int Id { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Registration Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime RegistrationDate { get; set; }

        [Required]
        [Display(Name = "Is Admin")]
        public bool IsAdmin { get; set; }
    }
}

s11-selfstudy/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using s11_selfstudy.Data;
using s11_selfstudy.Models;

namespace s11_selfstudy.Controllers
{
    public class CoursesController : Controller
    {
        private readonly s11_selfstudyContext _context;

        public CoursesController(s11_selfstudyContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
              return _context.Course != null ? 
                          View(await _context.Course.ToListAsync()) :
                          Problem("Entity set 's11_selfstudyContext.Course'  is null.");
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Stack,Description,Price,StackUrl,Logo")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Stack,Description,Price,StackUrl,Logo")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Course == null)
            {
                return Problem("Entity set 's11_selfstudyContext.Course'  is null.");
            }
            var course = await _context.Course.FindAsync(id);
            if (course != null)
            {
                _context.Course.Remove(course);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
          return (_context.Course?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

s11-selfstudy/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using s11_selfstudy.Models;
using System.Diagnostics;

namespace s11_selfstudy.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

s11-selfstudy/Views/Courses/Create.cshtml
@model s11_selfstudy.Models.Course

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center">Add Course</h1>

<div class="row">
    <div class="col-md-4 offset-md-4 fw-bold">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Stack" class="control-label"></label>
                @*<select asp-for="Stack" class="form-control"></select>*@
                <select asp-for="Stack" asp-items="Html.GetEnumSelectList<Stack>()" class="form-control"></select>
                <span asp-validation-for="Stack" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="StackUrl" class="control-label"></label>
                <input asp-for="StackUrl" class="form-control" />
                <span asp-validation-for="StackUrl" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group text-center">
                <button class="btn btn-success" type="submit">
                    Add Course
                </button>
                <button class="btn btn-danger" type="button">
                    <a class="text-light text-decoration-none" asp-action="Index">Back to Courses</a>
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

s11-selfstudy/Views/Courses/Delete.cshtml
@model s11_selfstudy.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stack)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stack)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StackUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StackUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

s11-selfstudy/Views/Courses/Details.cshtml
@model s11_selfstudy.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stack)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stack)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StackUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StackUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

s11-selfstudy/Views/Courses/Edit.cshtml
@model s11_selfstudy.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">Edit Course</h1>

<div class="row">
    <div class="col-md-4 offset-md-4 fw-bold">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group mb-3">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Stack" class="control-label"></label>
                @*<select asp-for="Stack" class="form-control"></select>*@
                <select asp-for="Stack" asp-items="Html.GetEnumSelectList<Stack>()" class="form-control"></select>
                <span asp-validation-for="Stack" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="StackUrl" class="control-label"></label>
                <input asp-for="StackUrl" class="form-control" />
                <span asp-validation-for="StackUrl" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group text-center">
                <button class="btn btn-success" type="submit">
                    Save
                </button>
                <button class="btn btn-danger" type="button">
                    <a class="text-light text-decoration-none" asp-action="Index">Back to Courses</a>
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

s11-selfstudy/Views/Courses/Index.cshtml
@model IEnumerable<s11_selfstudy.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<div class="d-flex justify-content-between my-5">
            <h1>Courses</h1>
            <button class="btn btn-success py-0">
                <a class="text-light text-decoration-none" asp-area="" asp-controller="Courses" asp-action="Create">Add New Course</a>
            </button>
        </div>

        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>
                        @Html.DisplayNameFor(model => model.Logo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Stack)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StackUrl)
                    </th>
                    <th>Actions:</th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td class="align-middle">
                        @if (item.Logo != null)
                        {
                            <img src="@Url.Content(item.Logo)" alt="Logo" style="height: 75px; width: 75px"/>
                        }
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                        <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Stack)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.StackUrl)
                    </td>
                    <td class="align-middle">
                        <button class="btn btn-warning fw-bold d-block w-100 mb-2">
                            <a class="text-dark text-decoration-none" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        </button>
                            <button class="btn btn-primary fw-bold d-block w-100 mb-2">
                            <a class="text-dark text-decoration-none" asp-action="Details" asp-route-id="@item.Id">Details</a>
                        </button>
                            <button class="btn btn-danger fw-bold d-block w-100 mb-2">
                                <a class="text-dark text-decoration-none" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </button>
                    </td>
                </tr>
        }
            </tbody>
        </table>

s11-selfstudy/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center my-5">
    <h1 class="display-4">Welcome to LaZuitt</h1>
</div>

<div class="text-center">
    <button class="btn btn-primary">
        <a class="nav-link text-light" asp-controller="Courses" asp-action="Index">
            Manage Courses
        </a>
    </button>
</div>

s11-selfstudy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - s11_selfstudy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/s11_selfstudy.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @*Change the navbar color to "bg-dark"*@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*Change the branding text to "LaZuitt" and the text color to "text-light"*@
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">LaZuitt</a>
                // ...
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @*Change the text color to "text-light" and the asp-controller/asp-action attributes*@
                            <a class="nav-link text-light" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            @*Change the text color to "text-light" and the asp-controller/asp-action attributes*@
                            <a class="nav-link text-light" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @*Remove the "container" class and add the following classes "bg-dark text-light text-center" and change the branding text to "LaZuitt"*@
        <div class="bg-dark text-light text-center">
            &copy; 2023 - LaZuitt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>